# Generated by Django 4.1.5 on 2023-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='league',
            field=models.CharField(choices=[('NFL', 'NFL'), ('MLB', 'MLB')], default='NFL', max_length=10),
        ),
        migrations.AlterField(
            model_name='stat',
            name='league',
            field=models.CharField(choices=[('NFL', 'NFL'), ('MLB', 'MLB')], default='NFL', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('NFL', 'NFL'), ('MLB', 'MLB')], default='NFL', max_length=10),
        ),
    ]
