# Generated by Django 4.1.5 on 2023-04-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0011_alter_result_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='num_games',
        ),
    ]
