# Generated by Django 4.1.7 on 2023-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subdir', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
