# Generated by Django 4.1.5 on 2023-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='appname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
