# Generated by Django 4.1.5 on 2023-02-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appslist', '0002_app_appname'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
