# Generated by Django 4.1.5 on 2024-02-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appslist', '0003_app_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
