parameters: {}
environment: {}
packages:
    - name: sample
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: hello
          binary: false
          main: ""
          runtime: python:default
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
    - name: scripts
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: load_mlb_odds
          binary: false
          main: ""
          runtime: python:default
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: load_mlb_scores
          binary: false
          main: ""
          runtime: python:default
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: django_test
          binary: false
          main: ""
          runtime: python:default
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}