# Generated by Django 4.1.5 on 2023-03-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0006_remove_contest_complete_contest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='active',
        ),
    ]
