# Generated by Django 4.1.5 on 2023-03-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0009_remove_result_league_remove_result_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='test_contest',
            field=models.BooleanField(default=False),
        ),
    ]
