# Generated by Django 4.1.5 on 2023-05-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0014_pick_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
