# Generated by Django 4.1.5 on 2023-05-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0016_remove_game_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(blank=True, max_length=10)),
                ('pts', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
