# Generated by Django 4.1.5 on 2023-03-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
                ('num_picks', models.IntegerField()),
                ('num_games', models.IntegerField()),
                ('wager', models.DecimalField(decimal_places=2, max_digits=6)),
                ('winner', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=10)),
                ('abbrev', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('winnings', models.DecimalField(decimal_places=2, max_digits=6)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=3)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_the_odds.contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('team_away', models.CharField(max_length=3)),
                ('team_home', models.CharField(max_length=3)),
                ('odds_away', models.IntegerField()),
                ('odds_home', models.IntegerField()),
                ('score_away', models.IntegerField()),
                ('score_home', models.IntegerField()),
                ('outcome_away', models.CharField(max_length=1)),
                ('outcome_home', models.CharField(max_length=1)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_the_odds.contest')),
            ],
        ),
    ]
