# Generated by Django 4.1.5 on 2023-03-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0003_alter_contest_winner_alter_game_odds_away_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='odds_away',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='odds_home',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_home',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
