# Generated by Django 4.1.5 on 2023-03-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0005_remove_contest_wager_remove_stat_winnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='complete',
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Complete', 'Complete')], default='Active', max_length=10),
        ),
    ]
