# Generated by Django 4.1.5 on 2023-04-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0012_remove_contest_num_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
