# Generated by Django 4.1.5 on 2023-05-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_odds', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
